name: dwr0001
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.3.1
  cupertino_icons: ^1.0.2
  http: ^0.12.0
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.0.7
  bezier_chart: ^1.0.16
  flutter_glow: ^0.2.0
  avatar_glow: ^2.0.1
  url_launcher: ^6.0.5
  pull_to_refresh: ^2.0.0
  flutter_session: ^0.1.1
  responsive_flutter: ^0.0.4
  charts_flutter: ^0.10.0
  flutter_staggered_grid_view: ^0.4.0
  full_screen_image: any
  flutter_plugin_pdf_viewer: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/pdf/mk/mk.pdf
    - assets/pdf/kk/kk.pdf
    - assets/pdf/sl/sl.pdf
    - assets/images/
    - images/bg.jpg
    - images/bg2.png
    - images/ic_launcher.png
    - assets/images/loading1.gif
    - assets/images/loading2.gif
    - assets/images/beach.png
    - assets/images/bg.png
    - assets/images/bg2.png
    - assets/images/search.png
    - assets/images/home.png
    - assets/images/waveup.png
    - assets/images/wavedown.png
    - assets/images/wavetab.png
    - assets/images/river.png
    - assets/images/cctv.png
    - assets/images/lineriver.png
    - assets/images/web.png
    - assets/images/contact.png
    - assets/images/river1.png
    - assets/images/river2.png
    - assets/images/river3.png
    - assets/images/wallpaper_new.jpeg
    - assets/banner/banner01/background02.png
    - assets/banner/banner01/sign_in.png
    - assets/banner/banner02/background03.png
    - assets/banner/banner02/background04.png
    - assets/banner/banner02/subhead01.png
    - assets/banner/banner02/choice01_mae_klong.png
    - assets/banner/banner02/choice02_salawin.png
    - assets/banner/banner02/choice03_kok.png
    - assets/banner/banner02/choice04_station.png
    - assets/banner/banner02/choice05_predict.png
    - assets/banner/banner02/choice06_project.png
    - assets/banner/banner02/subhead02.png
    - assets/banner/banner02/subhead03.png
    - assets/banner/banner02/subhead04.png
    - assets/banner/banner01/background01.png
    - assets/TabOne/cloud.png
    - assets/TabOne/cloud_rain.png
    - assets/TabOne/water_level.png
    - assets/TabOne/climate_inv.png
    - assets/TabOne/climate.png
    - assets/TabOne/hailstorm_inv.png
    - assets/TabOne/hailstorm.png
    - assets/TabOne/hailstorm_Gray.png
    - assets/TabOne/tide_inv.png
    - assets/TabOne/tide.png
    - assets/TabOne/tide_Gray.png
    - assets/TabOne/hailstrom_blue.png
    - assets/banner/bell/red.png
    - assets/banner/bell/green.png
    - assets/banner/bell/gray.png
    - assets/banner/bell/yellow.png
    - assets/banner/back_button/button_back.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Italic.ttf
          style: italic
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
